---
minecraft_bedrock_server_enabled: false

# directories
minecraft_bedrock_server_data_directory: "{{ docker_home }}/minecraft_bedrock_server"

# network
minecraft_bedrock_server_port: "19132"

# docker
minecraft_bedrock_server_container_name: minecraft-bedrock-server

# minecraft settings
minecraft_bedrock_server_name: "SuperCraft"
minecraft_bedrock_server_game_mode: "survival"
minecraft_bedrock_server_difficulty: "normal"
minecraft_bedrock_server_online_mode: "true"
