---
bitwarden_enabled: true
bitwarden_available_externally: true
bitwarden_data_directory: "{{ docker_home }}/bitwarden"
bitwarden_port_a: "19080"
bitwarden_port_b: "3012"
bitwarden_hostname: "bitwarden"
bitwarden_ip_whitelist: "192.168.1.0/24,98.42.126.77"

# Keep this token secret, this is password to access admin area of your server!
# This token can be anything, but it's recommended to use a long, randomly generated string of characters,
# for example running openssl rand -base64 48
bitwarden_admin_token: "{{ bitwarden }}"

# To create a user set this to "true", and reprovision the container by re-running the ansible-nas playbook.
# Once you have created your user, set to "false" and run one more time.
# Target just Bitwarden by running: ansible-playbook -i inventory nas.yml -b -K -t bitwarden
bitwarden_allow_signups: false

# specs
bitwarden_memory: 1g
bitwarden_backup_memory: 1g

# docker
bitwarden_container_name: bitwarden
bitwarden_backup_container_name: bitwarden-backup
