- name: pihole Docker Container
  docker_container:
    name:pihole
    image: pihole/pihole:latest
    pull: true
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
   dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    cap_add:
      - NET_ADMIN
  labels:
      traefik.backend: "pihole"
      traefik.frontend.rule: "Host:pihole.{{ ansible_nas_domain }}"
      traefik.enable: "false"
      traefik.port: "80"
