---
- name: Start Gluetun
  block:
    - name: Create Gluetun Directories
      ansible.builtin.file:
        path: "{{ gluetun_data_directory }}"
        state: directory

    - name: Gluetun Docker Container
      community.docker.docker_container:
        name: "{{ gluetun_container_name }}"
        image: "{{ gluetun_image }}:{{ gluetun_version }}"
        pull: true
        devices:
          - /dev/net/tun
        capabilities:
          - NET_ADMIN
        ports:
          - 8000:8000/tcp
          - 8888:8888/tcp # HTTP proxy
        env:
          VPN_SERVICE_PROVIDER: "{{ gluetun_vpn_service_provider }}"
          VPN_TYPE: "{{ gluetun_vpn_type }}"
          OPENVPN_USER: "{{ github_openvpn_username }}"
          OPENVPN_PASSWORD: "{{ github_openvpn_password }}"
          SERVER_REGIONS: "USA Los Angeles"
          # VPN_PORT_FORWARDING: "on"
          HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"derpydo"}'
          HTTPPROXY: "on"
          HTTPPROXY_LISTENING_ADDRESS: ":8888"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
  when: gluetun_enabled is true

- name: Stop Gluetun
  block:
    - name: Stop Gluetun
      community.docker.docker_container:
        name: "{{ gluetun_container_name }}"
        state: absent
  when: gluetun_enabled is false
