---
- name: Start Firefly
  block:
    - name: Create Firefly III Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ firefly_data_directory }}/mariadb"
        - "{{ firefly_data_directory }}/upload"
        - "{{ firefly_data_directory }}/export"
        - "{{ firefly_data_directory }}/importer"

    - name: Ensure Firefly III environment files exist
      ansible.builtin.copy:
        content: ""
        dest: "{{ item }}"
        force: false
      with_items:
        - "{{ firefly_data_directory }}/.env"
        - "{{ firefly_data_directory }}/importer/.env"

    - name: Create MySQL container for Firefly
      community.docker.docker_container:
        name: "{{ firefly_mysql_container_name }}"
        image: mariadb:10.9
        pull: true
        volumes:
          - "{{ firefly_data_directory }}/mariadb:/var/lib/mysql:rw"
        env:
          MYSQL_DATABASE: "firefly"
          MYSQL_USER: "firefly"
          MYSQL_PASSWORD: "{{ mariadb_password }}"
          MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
        restart_policy: unless-stopped
        memory: "{{ firefly_mysql_memory }}"

    - name: Wait for MySQL to init
      ansible.builtin.pause:
        seconds: 30

    - name: Create Firefly III container
      community.docker.docker_container:
        name: "{{ firefly_container_name }}"
        image: fireflyiii/core:latest
        pull: true
        volumes:
          - "{{ firefly_data_directory }}/export:/var/www/firefly-iii/storage/export:rw"
          - "{{ firefly_data_directory }}/upload:/var/www/firefly-iii/storage/upload:rw"
          - "{{ firefly_data_directory }}/.env:/var/www/html/.env:rw"
        links:
          - firefly-mysql:db
        ports:
          - "{{ firefly_port }}:8080"
        env:
          APP_URL: "https://{{ firefly_hostname }}.{{ ansible_nas_domain }}"
          TRUSTED_PROXIES: "**"
          APP_ENV: "local"
          APP_KEY: "{{ firefly_api_key }}"
          DB_CONNECTION: "mysql"
          DB_HOST: "db"
          DB_DATABASE: "firefly"
          DB_USERNAME: "firefly"
          DB_PASSWORD: "{{ mariadb_password }}"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped
        memory: "{{ firefly_memory }}"
        labels:
          traefik.enable: "{{ firefly_available_externally | string }}"
          traefik.http.routers.firefly.rule: "Host(`{{ firefly_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.firefly.tls.certresolver: "letsencrypt"
          traefik.http.routers.firefly.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.firefly.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.firefly.loadbalancer.server.port: "8080"

    - name: Create Firefly III Importer
      community.docker.docker_container:
        name: firefly-importer
        image: fireflyiii/data-importer:latest
        pull: true
        volumes:
          - "{{ firefly_data_directory }}/import:/import:rw"
          - "{{ firefly_data_directory }}/importer/.env:/var/www/html/.env:rw"
        ports:
          - "{{ firefly_importer_port }}:8080"
        env:
          FIREFLY_III_CLIENT_ID: "01a122d1-449c-70f9-a558-988d750263c6"
          VANITY_URL: "http://streamweaver:{{ firefly_port }}"
          FIREFLY_III_URL: "http://streamweaver:{{ firefly_port }}"
          # FIREFLY_III_ACCESS_TOKEN: "{{ firefly_api_key }}"
          TZ: "{{ ansible_nas_timezone }}"
        restart_policy: unless-stopped

  when: firefly_enabled is true

- name: Stop Firefly
  block:
    - name: Stop Firefly
      community.docker.docker_container:
        name: "{{ firefly_container_name }}"
        state: absent

    - name: Stop Firefly MySQL
      community.docker.docker_container:
        name: "{{ firefly_mysql_container_name }}"
        state: absent
  when: firefly_enabled is false
