---
- name: Start Exporters
  block:
    - name: Smartctl Exporter Docker Container
      community.docker.docker_container:
        name: "{{ stats_smartctl_container_name }}"
        image: "{{ stats_smartctl_docker_image_name }}:{{ stats_smartctl_docker_image_version }}"
        pull: true
        privileged: true
        ports:
          - "{{ stats_prometheus_smartctl_port }}:9902"
        restart_policy: unless-stopped
        memory: "{{ stats_prometheus_smartctl_memory }}"

    - name: Speedtest Exporter Docker Container
      community.docker.docker_container:
        name: "{{ stats_speedtest_container_name }}"
        image: "{{ stats_speedtest_docker_image_name }}:{{ stats_speedtest_docker_image_version }}"
        pull: true
        ports:
          "{{ stats_speedtest_exporter_port }}:9798"
        restart_policy: unless-stopped
        memory: "{{ stats_speedtest_exporter_memory }}"
      when: stats_internet_speed_test_enabled

    - name: SNMP Exporter Docker Container
      community.docker.docker_container:
        name: "{{ stats_snmp_exporter_container_name }}"
        image: "{{ stats_snmp_exporter_docker_image_name }}:{{ stats_snmp_exporter_docker_image_version }}"
        pull: true
        ports:
          - "{{ stats_snmp_exporter_port }}:9116"
        volumes:
          - "{{ docker_home }}/stats/files/:/etc/snmp_exporter/"
        command: "--config.file=/etc/snmp_exporter/snmp.yml"
        restart_policy: unless-stopped
      when: stats_snmp_exporter_enabled

    - name: PiHole Exporter Docker Container
      community.docker.docker_container:
        name: "{{ stats_pihole_exporter_container_name }}"
        image: "{{ stats_pihole_exporter_docker_image_name }}:{{ stats_pihole_exporter_docker_image_version }}"
        pull: true
        ports:
          - "{{ stats_pihole_exporter_port }}:9617"
        env:
          PIHOLE_HOSTNAME: "192.168.1.2"
          # PIHOLE_PASSWORD: ""
          PIHOLE_PORT: "888"
          PORT: "{{ stats_pihole_exporter_port }}"
        restart_policy: unless-stopped
      when: stats_pihole_exporter_enabled

  when: stats_enabled is true

- name: Stop Exporters
  block:
    - name: Stop Smartctl Exporter
      community.docker.docker_container:
        name: "{{ stats_smartctl_container_name }}"
        state: absent
    - name: Stop Speedtest Exporter
      community.docker.docker_container:
        name: "{{ stats_speedtest_container_name }}"
        state: absent
    - name: Stop SNMP Exporter
      community.docker.docker_container:
        name: "{{ stats_snmp_exporter_container_name }}"
        state: absent
    - name: Stop PiHole Exporter
      community.docker.docker_container:
        name: "{{ stats_pihole_exporter_container_name }}"
        state: absent
  when: stats_enabled is false
