---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yml

clients:
  - url: {{ promtail_loki_url }}
    tenant_id: 1

scrape_configs:
  - job_name: docker_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - target_label: hostname
        replacement: '{{ ansible_nas_hostname }}'  # Use the hostname from Ansible
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
# {% if plex_enabled %}
#   - job_name: plex_logs
#     file_sd_configs:
#       - files:
#         - "/plex/*.log"
#     relabel_configs:
#       - target_label: job
#         replacement: "plex"
#       - target_label: host
#         replacement: "{{ ansible_nas_hostname }}"
#       - target_label: application
#         replacement: "plex"
#       - target_label: service
#         replacement: "plex"
# {% endif %}
{% if plex_enabled %}
  - job_name: plex
    static_configs:
      - targets:
          - localhost
        labels:
          job: plex
          __path__: /plex/**/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<ts>\w{3} \w{3} [0-9]{1,2} [0-9:]{8}\.[0-9]{3}) (?P<level>[A-Z]+) (?P<component>[^:]+): (?P<msg>.*)'
      - timestamp:
          source: ts
          format: Jan _2 15:04:05.000
      - labels:
          level:
          component:
{% endif %}