---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yml

clients:
  - url: {{ promtail_loki_url }}
    tenant_id: 1

scrape_configs:
  - job_name: docker_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    static_configs:
      - targets:
          - localhost
        labels:
          job: "system_logs"
          host: "{{ ansible_hostname }}"  # Use the hostname from Ansible
          environment: "production"
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
