---
stats_enabled: true
stats_internet_speed_test_enabled: true
stats_prometheus_available_externally: false
stats_grafana_available_externally: false
stats_snmp_exporter_enabled: true
stats_pihole_exporter_enabled: true

# directories
stats_telegraf_config_directory: "{{ docker_home }}/stats/telegraf/config"
stats_prometheus_data_directory: "{{ docker_home }}/stats/prometheus/data"
stats_prometheus_config_directory: "{{ docker_home }}/stats/prometheus/config"
stats_grafana_data_directory: "{{ docker_home }}/stats/grafana/data"
stats_grafana_config_directory: "{{ docker_home }}/stats/grafana/config"

# network
stats_prometheus_port: "9090"
stats_telegraf_port: "9273"
stats_telegraf_influxdb_port: "8086"
stats_prometheus_smartctl_port: "9902"
stats_speedtest_exporter_port: "9798"
stats_prometheus_hostname: "prometheus"
stats_grafana_port: "3000"
stats_grafana_hostname: "grafana"
stats_snmp_exporter_port: "9116"
stats_pihole_exporter_port: "9617"

# docker:
stats_grafana_container_name: "stats-grafana"
stats_grafana_image_name: "grafana/grafana-oss"
stats_grafana_image_version: "latest"
stats_prometheus_container_name: "stats-prometheus"
stats_prometheus_image_name: "prom/prometheus"
stats_prometheus_image_version: "latest"
stats_telegraf_container_name: "stats-telegraf"
stats_telegraf_image_name: "telegraf"
stats_telegraf_image_version: "latest"
stats_smartctl_container_name: "stats-smartctl"
stats_smartctl_docker_image_name: "matusnovak/prometheus-smartctl"
stats_smartctl_docker_image_version: "latest"
stats_speedtest_container_name: "stats-speedtest"
stats_speedtest_docker_image_name: "miguelndecarvalho/speedtest-exporter"
stats_speedtest_docker_image_version: "latest"
stats_snmp_exporter_container_name: "snmp-exporter"
stats_snmp_exporter_docker_image_name: "prom/snmp-exporter"
stats_snmp_exporter_docker_image_version: "latest"
stats_pihole_exporter_container_name: "pihole-exporter"
stats_pihole_exporter_docker_image_name: "ekofr/pihole-exporter"
stats_pihole_exporter_docker_image_version: "latest"

# specs
stats_telegraf_memory: 1g
stats_prometheus_memory: 1g
stats_prometheus_smartctl_memory: 1g
stats_speedtest_exporter_memory: 256m
stats_grafana_memory: 1g

# config
stats_prometheus_retention_time: 365d
stats_prometheus_retention_size: 30GB
stats_collection_interval: 15s
stats_speedtest_collection_interval: 1h

# uncomment to scrape more hosts
# stats_prometheus_additional_hosts:
#  - 192.168.1.1:9100

# uncomment to scrape metrics from HomeAssistant. You'll need to create a long lived access token.
stats_hass_long_lived_access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI2NmE4ZGU5OWQ1ZjQ0ZjhjOTIwZTRlMjgzZjMwMjNiZCIsImlhdCI6MTcxNjU5NzE5NywiZXhwIjoyMDMxOTU3MTk3fQ.HvLuMOhpEy16h1hLNb3GPEu5sh2x7fqJKDC-BvEL5BY
