---
- name: Start Homeassistant
  block:
    - name: Create Home Assistant Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homeassistant_data_directory }}/config"

    - name: Home Assistant Docker Container
      community.docker.docker_container:
        name: "{{ homeassistant_container_name }}"
        image: "{{ homeassistant_image_name }}:{{ homeassistant_image_version }}"
        pull: true
        privileged: true
        volumes:
          - "{{ homeassistant_data_directory }}/config:/config:rw"
          - "/dev:/dev"
          - "/run/dbus:/run/dbus:ro"
        network_mode: host
        restart_policy: unless-stopped
        env:
          TZ: "{{ ansible_nas_timezone }}"
        dns_servers:
          - "192.168.1.2"
          - "192.168.1.1"
        labels:
          traefik.enable: "{{ homeassistant_available_externally | string }}"
          traefik.http.routers.homeassistant.rule: "Host(`{{ homeassistant_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homeassistant.tls.certresolver: "letsencrypt"
          traefik.http.routers.homeassistant.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homeassistant.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.homeassistant.service: "homeassistant"
          traefik.http.routers.homeassistant.middlewares: "homeassistant-ipwhitelist@docker"
          traefik.http.routers.homeassistant-ws.rule: "Host(`{{ homeassistant_hostname }}.{{ ansible_nas_domain }}`) && Path(`/notifications/hub`)"
          traefik.http.routers.homeassistant-ws.tls.certresolver: "letsencrypt"
          traefik.http.routers.homeassistant-ws.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homeassistant-ws.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.homeassistant-ws.service: "homeassistant-ws"
          traefik.http.routers.homeassistant-ws.middlewares: "homeassistant-ipwhitelist@docker"
          traefik.http.services.homeassistant.loadbalancer.server.port: "80"
          traefik.http.services.homeassistant-ws.loadbalancer.server.port: "8123"
          traefik.http.middlewares.homeassistant-ipwhitelist.ipallowlist.sourcerange: "{{ homeassistant_ip_whitelist }}"
        memory: "{{ homeassistant_memory }}"
    - name: Music Assistant Docker Container
      community.docker.docker_container:
        name: "music-assistant-server"
        image: "ghcr.io/music-assistant/server:latest"
        pull: true
        volumes:
          - "{{ docker_home }}/music-assistant-server/data:/data/"
          - /mnt/storage/music:/media:ro
        network_mode: host
        restart_policy: unless-stopped
        env:
          TZ: "{{ ansible_nas_timezone }}"
          LOG_LEVEL: info

    - name: Create Wyoming directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ wyoming_piper_data_directory }}"
        - "{{ wyoming_whisper_data_directory }}"
        - "{{ wyoming_openwakeword_data_directory }}"

    - name: Wyoming Piper Docker Container
      community.docker.docker_container:
        name: "{{ wyoming_piper_container_name }}"
        image: "{{ wyoming_piper_image }}"
        pull: true
        ports:
          - "{{ wyoming_piper_port }}:10200"
        volumes:
          - "{{ wyoming_piper_data_directory }}:/data:rw"
        command: "--voice {{ wyoming_piper_voice }}"
        restart_policy: unless-stopped

    - name: Wyoming Whisper Docker Container
      community.docker.docker_container:
        name: "{{ wyoming_whisper_container_name }}"
        image: "{{ wyoming_whisper_image }}"
        pull: true
        ports:
          - "{{ wyoming_whisper_port }}:10300"
        volumes:
          - "{{ wyoming_whisper_data_directory }}:/data:rw"
        command: "--model {{ wyoming_whisper_model }} --language {{ wyoming_whisper_language }}"
        restart_policy: unless-stopped

    - name: Wyoming OpenWakeWord Docker Container
      community.docker.docker_container:
        name: "{{ wyoming_openwakeword_container_name }}"
        image: "{{ wyoming_openwakeword_image }}"
        pull: true
        ports:
          - "{{ wyoming_openwakeword_port }}:10400"
        volumes:
          - "{{ wyoming_openwakeword_data_directory }}:/data:rw"
        command: "--preload-model {{ wyoming_openwakeword_model }}"
        restart_policy: unless-stopped

  when: homeassistant_enabled is true

- name: Stop homeassistant
  block:
    - name: Stop homeassistant
      community.docker.docker_container:
        name: "{{ homeassistant_container_name }}"
        state: absent
    - name: Stop Wyoming Piper
      community.docker.docker_container:
        name: "{{ wyoming_piper_container_name }}"
        state: absent
    - name: Stop Wyoming Whisper
      community.docker.docker_container:
        name: "{{ wyoming_whisper_container_name }}"
        state: absent
    - name: Stop Wyoming OpenWakeWord
      community.docker.docker_container:
        name: "{{ wyoming_openwakeword_container_name }}"
        state: absent
  when: homeassistant_enabled is false
