---
- name: Start wireguard
  block:
    - name: Wireguard Docker Container
      community.docker.docker_container:
        name: "wireguard"
        image: "ghcr.io/wg-easy/wg-easy:15"
        pull: true
        volumes:
          # - "{{ docker_home }}/wireguard-server/config:/config"
          - "{{ docker_home }}/wireguard:/etc/wireguard"
          - "/lib/modules:/lib/modules:ro"
          - "{{ docker_home }}/wireguard/hosts:/etc/hosts:rw"
        ports:
          - "51820:51820/udp"
          - "51821:51821/tcp"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "1000"
          PGID: "1000"
          SERVERURL: jakesticka.duckdns.org
          SERVERPORT: "51820"
          PORT: "51821"
          INSECURE: "true"
          PEERS: "1"
          PEERDNS: "192.168.1.2"
          INIT_DNS: "192.168.1.2, 192.168.1.1"
          ALLOWEDIPS: 192.168.1.0/24
          WG_DEFAULT_DNS: "192.168.1.2"
        restart_policy: unless-stopped
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
        capabilities:
          - NET_ADMIN
          - SYS_MODULE

  when: wireguard_enabled is true

- name: Stop wireguard
  block:
    - name: Stop wireguard
      community.docker.docker_container:
        name: "wireguard"
        state: absent
  when: wireguard_enabled is false
