name: StreamWeaver

on:
  workflow_dispatch:
    inputs:
      tags:
        required: false
        type: string
        default: "all"

jobs:
  call-template:
    uses: ./.github/workflows/ansible-playbook-template.yml
    with:
      runner: 'streamweaver'
      tags: ${{ github.event.inputs.tags || 'all' }}
