name: Zima

on:
  workflow_dispatch:
    inputs:
      tags:
        required: false
        type: string
        default: "all"

jobs:
  call-template:
    uses: ./.github/workflows/ansible-playbook-template.yml
    with:
      runner: "self-hosted,linux,zima"
      tags: ${{ github.event.inputs.tags || 'all' }}
      # inventory: "hosts.ini"    # optional